import { toolIllustrations } from '../assets/registry';

export const archiveConfig = {
  jobType: 'archive',
  defaultOperation: 'create',
  defaultFormat: 'zip',
  capability: 'archive.zip',
  eyebrow: 'More tools / Archive Center',
  title: 'Compress, inspect, and extract archives.',
  description: 'Create and extract ZIP, TAR, and GZ archives locally. 7Z is available when the 7z binary is on PATH.',
  primaryAction: 'Build archive',
  primaryIcon: 'archive',
  tone: 'purple',
  art: toolIllustrations.archive,
  accept: '.zip,.tar,.gz,.tgz,.7z,*/*',
  tabs: ['Create archive', 'Extract', 'Inspect'],
  features: [
    { title: 'Create archive', icon: 'archive', short: 'Bundle local files', description: 'Configure format, compression level, folder structure, and output naming.', operation: 'create', format: 'zip', capability: 'archive.zip' },
    { title: 'Extract files', icon: 'download', short: 'Extract safely', description: 'Extract an archive with zip-slip protection into a downloadable package. Format is auto-detected from magic bytes and extension.', operation: 'extract', format: 'auto', capability: 'archive.zip' },
    { title: 'Create TAR', icon: 'scissors', short: 'TAR package', description: 'Bundle files into a TAR archive.', operation: 'create', format: 'tar', capability: 'archive.tar', options: { format: 'tar' } },
    { title: 'Create GZ', icon: 'minimize', short: 'Gzip a file', description: 'Compress a single file with gzip.', operation: 'create', format: 'gz', capability: 'archive.gz', options: { format: 'gz' }, multiple: false },
    { title: 'Inspect contents', icon: 'eye', short: 'Browse without extract', description: 'List files, folders, and sizes inside an archive.', operation: 'inspect', capability: 'archive.zip' },
    { title: 'Create 7Z', icon: 'shield', short: '7-Zip when available', description: 'Create a 7Z archive using the local 7z binary when present.', operation: 'create', format: '7z', capability: 'archive.7z', options: { format: '7z' } },
  ],
  extraActions: [],
};

export const textConfig = {
  jobType: 'text',
  defaultOperation: 'cleanup',
  capability: 'text.cleanup',
  eyebrow: 'More tools / Text & OCR',
  title: 'Extract, compare, and clean text.',
  description: 'Clean text, convert case, count words, and run developer-friendly text utilities. OCR is unavailable without a dedicated engine.',
  primaryAction: 'Run text tool',
  primaryIcon: 'scan',
  tone: 'cyan',
  art: toolIllustrations.text,
  accept: '.txt,.json,.md,.csv,text/*',
  tabs: ['OCR', 'Text cleaner', 'Compare', 'Analyze'],
  features: [
    { title: 'Image OCR', icon: 'scan', short: 'Not available', description: 'OCR requires an external engine and is unavailable in this build.', operation: 'ocr', capability: 'text.ocr', allowEmpty: true, clientOnly: true, clientMessage: 'OCR is not available: no OCR engine is bundled.' },
    { title: 'PDF OCR', icon: 'file', short: 'Not available', description: 'OCR requires an external engine and is unavailable in this build.', operation: 'ocr', capability: 'text.ocr', allowEmpty: true, clientOnly: true, clientMessage: 'OCR is not available: no OCR engine is bundled.' },
    { title: 'Text cleaner', icon: 'wand', short: 'Normalize formatting', description: 'Remove duplicated spaces, broken lines, and hidden characters.', operation: 'cleanup', capability: 'text.cleanup' },
    { title: 'Word counter', icon: 'text', short: 'Analyze content', description: 'Count words, characters, lines, and paragraphs.', operation: 'word-count', capability: 'text.cleanup' },
    { title: 'Case converter', icon: 'refresh', short: 'Change text style', description: 'Convert text between common case styles.', operation: 'case', capability: 'text.cleanup', options: { caseMode: 'title' } },
    { title: 'Hash text', icon: 'lock', short: 'SHA-256 digest', description: 'Hash file contents with SHA-256.', operation: 'hash', capability: 'text.hash', options: { algorithm: 'sha256' } },
  ],
  extraActions: [],
};

export const audioConfig = {
  jobType: 'audio',
  defaultOperation: 'convert',
  capability: 'audio.convert',
  eyebrow: 'More tools / Audio Lab',
  title: 'Shape audio with a focused waveform UI.',
  description: 'Convert, trim, and normalize audio when ffmpeg is installed. Missing binaries surface as Unavailable.',
  primaryAction: 'Process audio',
  primaryIcon: 'audio',
  tone: 'purple',
  art: toolIllustrations.audio,
  accept: 'audio/*,.mp3,.wav,.flac,.ogg,.m4a,.aac',
  tabs: ['Convert', 'Trim', 'Enhance', 'Metadata'],
  features: [
    { title: 'Convert audio', icon: 'swap', short: 'Change audio format', description: 'Select MP3, WAV, FLAC, AAC, OGG, or M4A output presets.', operation: 'convert', capability: 'audio.convert', options: { format: 'mp3' } },
    { title: 'Trim clip', icon: 'scissors', short: 'Select a time range', description: 'Trim audio with start/duration options.', operation: 'trim', capability: 'audio.trim', options: { start: '0', duration: '30' } },
    { title: 'Normalize volume', icon: 'audio', short: 'Balance loudness', description: 'Apply loudness normalization via ffmpeg.', operation: 'normalize', capability: 'audio.normalize' },
    { title: 'Inspect media', icon: 'eye', short: 'Probe streams', description: 'Inspect codecs and duration with ffprobe.', operation: 'inspect', capability: 'media.inspect' },
    { title: 'Extract vocals', icon: 'wand', short: 'Not supported', description: 'ML vocal separation is not supported in this local build.', operation: 'extract-vocals', capability: 'audio.extract-vocals', clientOnly: true, clientMessage: 'Vocal separation is not supported in this local build.' },
    { title: 'Quality convert', icon: 'settings', short: 'High quality encode', description: 'Convert with maximum quality preset.', operation: 'convert', capability: 'audio.convert', options: { format: 'flac', quality: 'max' } },
  ],
  extraActions: [],
};

export const colorConfig = {
  jobType: 'image',
  defaultOperation: 'convert',
  // Color studio stays mostly client-visual; image palette uses real image ops when files provided
  capability: 'image.convert',
  eyebrow: 'More tools / Color Studio',
  title: 'Build palettes and validate contrast.',
  description: 'Color picking and contrast checks stay local in the browser. Image palette extraction uses the image engine when a file is provided.',
  primaryAction: 'Process image colors',
  primaryIcon: 'palette',
  tone: 'cyan',
  art: toolIllustrations.color,
  accept: 'image/*',
  tabs: ['Palette', 'Gradient', 'Contrast', 'Convert'],
  features: [
    { title: 'Color picker', icon: 'droplet', short: 'Inspect a color', description: 'Use system color inputs in the browser; no server round-trip required.', operation: 'convert', clientOnly: true, allowEmpty: true, clientMessage: 'Use the browser color controls in this panel — no server job.' },
    { title: 'Palette generator', icon: 'palette', short: 'Create a color system', description: 'Client-side palette helpers; upload optional.', operation: 'convert', clientOnly: true, allowEmpty: true, clientMessage: 'Palette tools run in the browser only.' },
    { title: 'Gradient builder', icon: 'wand', short: 'Compose gradients', description: 'Design gradients in the UI without a backend job.', operation: 'convert', clientOnly: true, allowEmpty: true, clientMessage: 'Gradients are designed in the browser only.' },
    { title: 'Contrast checker', icon: 'eye', short: 'Check WCAG levels', description: 'Compare colors locally in the interface.', operation: 'convert', clientOnly: true, allowEmpty: true, clientMessage: 'Contrast checks run in the browser only.' },
    { title: 'Image palette', icon: 'image', short: 'Optimize source image', description: 'Optimize an uploaded image via Sharp for palette sampling workflows.', operation: 'optimize', capability: 'image.compress' },
    { title: 'Strip metadata', icon: 'code', short: 'Clean image exports', description: 'Remove metadata from images before sharing.', operation: 'strip-metadata', capability: 'image.strip-metadata' },
  ],
  extraActions: [],
};

export const securityConfig = {
  jobType: 'security',
  defaultOperation: 'hash',
  capability: 'security.hash',
  eyebrow: 'More tools / Security Lab',
  title: 'Inspect files and generate secure values.',
  description: 'Generate checksums, inspect magic-byte signatures and metadata, and create strong passwords. Password cracking is not supported.',
  primaryAction: 'Run security check',
  primaryIcon: 'shield',
  tone: 'green',
  art: toolIllustrations.security,
  accept: '*/*',
  tabs: ['Hash', 'Metadata', 'Passwords', 'Inspect'],
  features: [
    { title: 'File hash', icon: 'shield', short: 'Generate checksum', description: 'MD5, SHA-1, SHA-256, and SHA-512 digests.', operation: 'hash', capability: 'security.hash', options: { algorithms: ['md5', 'sha1', 'sha256', 'sha512'] } },
    { title: 'Compare checksums', icon: 'check', short: 'Verify integrity', description: 'Compare a file digest against an expected hex value you enter below.', operation: 'compare', capability: 'security.hash', options: { algorithm: 'sha256' } },
    { title: 'Metadata inspector', icon: 'eye', short: 'Review hidden data', description: 'Display size, MIME, and image EXIF presence.', operation: 'metadata', capability: 'security.metadata' },
    { title: 'Metadata scrubber', icon: 'trash', short: 'Strip image metadata', description: 'Create a clean image copy without metadata.', jobType: 'image', operation: 'strip-metadata', capability: 'image.strip-metadata', accept: 'image/*' },
    { title: 'Password generator', icon: 'key', short: 'Build strong passwords', description: 'Cryptographically secure password generation.', operation: 'password', capability: 'security.hash', allowEmpty: true, requiresFiles: false, options: { length: 20, symbols: true } },
    { title: 'File signature', icon: 'file', short: 'Inspect file type', description: 'Compare extension and magic-byte signatures.', operation: 'signature', capability: 'security.signature' },
  ],
  extraActions: [],
};
